# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/diego/Downloads/DMRGHandsOn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/diego/Downloads/DMRGHandsOn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/diego/Downloads/DMRGHandsOn/CMakeFiles /home/diego/Downloads/DMRGHandsOn/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/diego/Downloads/DMRGHandsOn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_renormalize

# Build rule for target.
test_renormalize: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_renormalize
.PHONY : test_renormalize

# fast build rule for target.
test_renormalize/fast:
	$(MAKE) -f CMakeFiles/test_renormalize.dir/build.make CMakeFiles/test_renormalize.dir/build
.PHONY : test_renormalize/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/build
.PHONY : common/fast

modules/DMRG.o: modules/DMRG.cpp.o

.PHONY : modules/DMRG.o

# target to build an object file
modules/DMRG.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/modules/DMRG.cpp.o
.PHONY : modules/DMRG.cpp.o

modules/DMRG.i: modules/DMRG.cpp.i

.PHONY : modules/DMRG.i

# target to preprocess a source file
modules/DMRG.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/modules/DMRG.cpp.i
.PHONY : modules/DMRG.cpp.i

modules/DMRG.s: modules/DMRG.cpp.s

.PHONY : modules/DMRG.s

# target to generate assembly for a file
modules/DMRG.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/modules/DMRG.cpp.s
.PHONY : modules/DMRG.cpp.s

modules/block.o: modules/block.cpp.o

.PHONY : modules/block.o

# target to build an object file
modules/block.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/modules/block.cpp.o
.PHONY : modules/block.cpp.o

modules/block.i: modules/block.cpp.i

.PHONY : modules/block.i

# target to preprocess a source file
modules/block.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/modules/block.cpp.i
.PHONY : modules/block.cpp.i

modules/block.s: modules/block.cpp.s

.PHONY : modules/block.s

# target to generate assembly for a file
modules/block.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/modules/block.cpp.s
.PHONY : modules/block.cpp.s

modules/model.o: modules/model.cpp.o

.PHONY : modules/model.o

# target to build an object file
modules/model.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/modules/model.cpp.o
.PHONY : modules/model.cpp.o

modules/model.i: modules/model.cpp.i

.PHONY : modules/model.i

# target to preprocess a source file
modules/model.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/modules/model.cpp.i
.PHONY : modules/model.cpp.i

modules/model.s: modules/model.cpp.s

.PHONY : modules/model.s

# target to generate assembly for a file
modules/model.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/modules/model.cpp.s
.PHONY : modules/model.cpp.s

modules/service.o: modules/service.cpp.o

.PHONY : modules/service.o

# target to build an object file
modules/service.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/modules/service.cpp.o
.PHONY : modules/service.cpp.o

modules/service.i: modules/service.cpp.i

.PHONY : modules/service.i

# target to preprocess a source file
modules/service.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/modules/service.cpp.i
.PHONY : modules/service.cpp.i

modules/service.s: modules/service.cpp.s

.PHONY : modules/service.s

# target to generate assembly for a file
modules/service.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/modules/service.cpp.s
.PHONY : modules/service.cpp.s

modules/sys.o: modules/sys.cpp.o

.PHONY : modules/sys.o

# target to build an object file
modules/sys.cpp.o:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/modules/sys.cpp.o
.PHONY : modules/sys.cpp.o

modules/sys.i: modules/sys.cpp.i

.PHONY : modules/sys.i

# target to preprocess a source file
modules/sys.cpp.i:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/modules/sys.cpp.i
.PHONY : modules/sys.cpp.i

modules/sys.s: modules/sys.cpp.s

.PHONY : modules/sys.s

# target to generate assembly for a file
modules/sys.cpp.s:
	$(MAKE) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/modules/sys.cpp.s
.PHONY : modules/sys.cpp.s

test/test_renormalize.o: test/test_renormalize.cpp.o

.PHONY : test/test_renormalize.o

# target to build an object file
test/test_renormalize.cpp.o:
	$(MAKE) -f CMakeFiles/test_renormalize.dir/build.make CMakeFiles/test_renormalize.dir/test/test_renormalize.cpp.o
.PHONY : test/test_renormalize.cpp.o

test/test_renormalize.i: test/test_renormalize.cpp.i

.PHONY : test/test_renormalize.i

# target to preprocess a source file
test/test_renormalize.cpp.i:
	$(MAKE) -f CMakeFiles/test_renormalize.dir/build.make CMakeFiles/test_renormalize.dir/test/test_renormalize.cpp.i
.PHONY : test/test_renormalize.cpp.i

test/test_renormalize.s: test/test_renormalize.cpp.s

.PHONY : test/test_renormalize.s

# target to generate assembly for a file
test/test_renormalize.cpp.s:
	$(MAKE) -f CMakeFiles/test_renormalize.dir/build.make CMakeFiles/test_renormalize.dir/test/test_renormalize.cpp.s
.PHONY : test/test_renormalize.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test_renormalize"
	@echo "... common"
	@echo "... modules/DMRG.o"
	@echo "... modules/DMRG.i"
	@echo "... modules/DMRG.s"
	@echo "... modules/block.o"
	@echo "... modules/block.i"
	@echo "... modules/block.s"
	@echo "... modules/model.o"
	@echo "... modules/model.i"
	@echo "... modules/model.s"
	@echo "... modules/service.o"
	@echo "... modules/service.i"
	@echo "... modules/service.s"
	@echo "... modules/sys.o"
	@echo "... modules/sys.i"
	@echo "... modules/sys.s"
	@echo "... test/test_renormalize.o"
	@echo "... test/test_renormalize.i"
	@echo "... test/test_renormalize.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

